// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz8uwN7U3TYukKYxl8C9YYc7KtC6GvkYw',
    appId: '1:400610893610:web:52e5d57b414feb665a0853',
    messagingSenderId: '400610893610',
    projectId: 'assetmanager-af9af',
    authDomain: 'assetmanager-af9af.firebaseapp.com',
    storageBucket: 'assetmanager-af9af.appspot.com',
    measurementId: 'G-YH6PVC7NSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByTxZi5Tv203vhPbdIiAmNWYzoQIno-W0',
    appId: '1:400610893610:android:899d719dac95a4975a0853',
    messagingSenderId: '400610893610',
    projectId: 'assetmanager-af9af',
    storageBucket: 'assetmanager-af9af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO-MMfyZQnZHlvvsSa5EkWL-IuFB_3pdI',
    appId: '1:400610893610:ios:3968901bea3e61595a0853',
    messagingSenderId: '400610893610',
    projectId: 'assetmanager-af9af',
    storageBucket: 'assetmanager-af9af.appspot.com',
    iosBundleId: 'com.example.assetStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO-MMfyZQnZHlvvsSa5EkWL-IuFB_3pdI',
    appId: '1:400610893610:ios:3968901bea3e61595a0853',
    messagingSenderId: '400610893610',
    projectId: 'assetmanager-af9af',
    storageBucket: 'assetmanager-af9af.appspot.com',
    iosBundleId: 'com.example.assetStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz8uwN7U3TYukKYxl8C9YYc7KtC6GvkYw',
    appId: '1:400610893610:web:3a5a17a012b717b55a0853',
    messagingSenderId: '400610893610',
    projectId: 'assetmanager-af9af',
    authDomain: 'assetmanager-af9af.firebaseapp.com',
    storageBucket: 'assetmanager-af9af.appspot.com',
    measurementId: 'G-11327BVX5Q',
  );

}